install:
 - brew update && brew upgrade swiftlint
 
language: swift
osx_image: xcode12.2

xcode_project: GHFollowers.xcodeproj
xcode_scheme: GHFollowers
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 12 Pro

script:
 - swiftlint
 - xcodebuild clean build -project 'GHFollowers.xcodeproj' -scheme 'GHFollowers' -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.2'
