name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install swiftlint
      run: brew install swiftlint

    - name: Force Xcode 12.1
      run: sudo xcode-select -switch /Applications/Xcode_12.1.app

    - name: Build app
      if: steps.cache.outputs.cache-hit != 'true'
      run: xcodebuild -project 'GHFollowers.xcodeproj' -scheme 'GHFollowers' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO | xcpretty
    
    - name: Run tests
      if: steps.cache.outputs.cache-hit != 'true'
      run: xcodebuild -project 'GHFollowers.xcodeproj' -scheme 'GHFollowers' -destination 'platform=iOS Simulator,name=iPhone 12 Pro' test | xcpretty
